services:
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8898:8080"
