services:
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8898:8080"
